# Tests then Publishes to PyPi
name: "Test & Upload to PyPi"
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Upgrade Pip"
        run: |
          python3 -m pip install --upgrade pip
      - name: "Install Requirements"
          python3 -m pip install setuptools wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 setup.py install
      # Checks if it correctly modifies data and checks performance
      - name: "Test Package"
        run: |
          python3 -m unittest tests/readwrite.py
      # Build for upload
      - name: "Build"
        run: |
          python3 setup.py sdist bdist_wheel

      # Uploads to PyPi
      - name: "Publish package"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}     
